### ISSUE TITLE
Import errors for formatting 

### ISSUE THREAD

**Issue by rsrikant1982** [apigee/apigeelint#271]
Getting import errors when trying to format 

**apigeelint -s apiproxy/ -f table.js**
/usr/lib/node_modules/apigeelint/lib/package/third_party/formatters/table.js:11
const chalk = require("chalk"),
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/apigeelint/node_modules/chalk/source/index.js from /usr/lib/node_modules/apigeelint/lib/package/third_party/formatters/table.js not supported.
Instead change the require of index.js in /usr/lib/node_modules/apigeelint/lib/package/third_party/formatters/table.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/lib/node_modules/apigeelint/lib/package/third_party/formatters/table.js:11:15)
    at getFormatter (/usr/lib/node_modules/apigeelint/lib/package/bundleLinter.js:168:14)
    at /usr/lib/node_modules/apigeelint/lib/package/bundleLinter.js:102:19
    at processFileSystem (/usr/lib/node_modules/apigeelint/lib/package/Bundle.js:230:5)
    at new Bundle (/usr/lib/node_modules/apigeelint/lib/package/Bundle.js:302:5)
    at Object.lint (/usr/lib/node_modules/apigeelint/lib/package/bundleLinter.js:71:3)
    at Object.<anonymous> (/usr/lib/node_modules/apigeelint/cli.js:89:4) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.1.0

**Comment by gbucknel** [comment]
hi @rsrikant1982 , I think it's pulling in chalk v5.0.0 and that's breaking it. If you downgrade chalk to 4.1.2 it works again.

**Comment by apcacher** [comment]
PR submitted: https://github.com/apigee/apigeelint/pull/272

**Comment by ssvaidyanathan** [comment]
Fixed in v2.11.0
